conveyor:
  dir_a_pin: 28
  dir_b_pin: 29
  pwm_pin: 24
  refresh_rate: 10

drive_motor:
  left_motor_sleep_pin: 22
  right_motor_sleep_pin: 21
  refresh_rate: 50

firing_wheel:
  output_pin: 25
  refresh_rate: 10

gate_servo_sb_node:
  closed_angle: 1500 # pulsewidth to achieve desired gate closed angle [us]
  open_angle: 1000 # pulsewidth to achieve desired gate open angle [us]
  open_time: 0.1 # [s]
  refresh_rate: 10
  sb_driver_path: "/dev/servoblaster"
  sb_servo_number: 0 # BCM pin #4

gate_solenoid:
  gate_open_time: 0.1 # [s]
  output_pin: 26
  refresh_rate: 10

roller:
  dir_a_pin: 4
  dir_b_pin: 5
  pwm_pin: 23
  refresh_rate: 10
