conveyor:
  dir_a_pin: 255 # not used
  dir_b_pin: 255 # not used
  pwm_pin: 24
  refresh_rate: 10

drive_motor:
  left_motor_sleep_pin: 255 # not used
  right_motor_sleep_pin: 255 # not used
  refresh_rate: 50

firing_wheel:
  output_pin: 25
  refresh_rate: 10

gate_servo_sb_node:
  closed_angle: 2000 # pulsewidth to achieve desired gate closed angle [us]
  open_angle: 2300 # pulsewidth to achieve desired gate open angle [us]
  open_time: 0.25 # [s]
  periodic_time: 0.5 # [s]
  refresh_rate: 10
  sb_driver_path: "/dev/servoblaster"
  sb_servo_number: 1 # BCM GPIO pin #17

gate_solenoid:
  gate_open_time: 0.1 # [s]
  output_pin: 255 # not used
  refresh_rate: 10

roller:
  dir_a_pin: 255 # not used
  dir_b_pin: 255 # not used
  pwm_pin: 23
  refresh_rate: 10
